# Generated by Django 2.0.2 on 2018-05-17 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zinc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chain',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('sequence', models.TextField()),
                ('pdb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zinc.Pdb')),
            ],
            options={
                'db_table': 'chains',
            },
        ),
    ]
