# Generated by Django 2.0.2 on 2018-09-05 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zinc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zincsite',
            name='code',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
