# Generated by Django 2.0.2 on 2018-05-18 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zinc', '0002_chain'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZincSite',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('pdb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zinc.Pdb')),
            ],
            options={
                'db_table': 'zinc_sites',
            },
        ),
    ]
