# Generated by Django 2.0.2 on 2018-05-18 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zinc', '0003_zincsite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metal',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('z', models.FloatField()),
                ('element', models.CharField(max_length=8)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zinc.ZincSite')),
            ],
            options={
                'db_table': 'metals',
            },
        ),
    ]
