# Generated by Django 2.0.2 on 2018-06-25 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zinc', '0003_zincsite_cluster'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdb',
            name='assembly',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
