# Generated by Django 2.0.2 on 2018-07-16 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zinc', '0004_pdb_assembly'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChainCluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'chain_clusters',
            },
        ),
        migrations.CreateModel(
            name='ZincSiteCluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'zincsite_clusters',
            },
        ),
        migrations.AlterField(
            model_name='chain',
            name='cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zinc.ChainCluster'),
        ),
        migrations.AlterField(
            model_name='zincsite',
            name='cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zinc.ZincSiteCluster'),
        ),
    ]
