# Generated by Django 2.0.2 on 2018-05-18 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zinc', '0004_metal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atom',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('atom_id', models.IntegerField()),
                ('name', models.CharField(max_length=32)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('z', models.FloatField()),
                ('element', models.CharField(max_length=8)),
                ('charge', models.FloatField()),
                ('bfactor', models.FloatField()),
                ('liganding', models.BooleanField()),
            ],
            options={
                'db_table': 'atoms',
            },
        ),
        migrations.CreateModel(
            name='Residue',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
                ('residue_id', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=128)),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zinc.Chain')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zinc.ZincSite')),
            ],
            options={
                'db_table': 'residues',
            },
        ),
        migrations.AddField(
            model_name='atom',
            name='residue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zinc.Residue'),
        ),
    ]
