# Generated by Django 2.0.2 on 2018-07-18 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zinc', '0005_auto_20180716_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chain',
            name='cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zinc.ChainCluster'),
        ),
        migrations.AlterField(
            model_name='zincsite',
            name='cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zinc.ZincSiteCluster'),
        ),
    ]
