# Generated by Django 2.0.2 on 2018-05-18 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zinc', '0005_auto_20180518_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residue',
            name='chain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='zinc.Chain'),
        ),
    ]
