# Generated by Django 2.2 on 2019-06-02 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pdb',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=1024)),
                ('classification', models.CharField(blank=True, max_length=1024, null=True)),
                ('keywords', models.CharField(blank=True, max_length=2048, null=True)),
                ('deposition_date', models.DateField(blank=True, null=True)),
                ('resolution', models.FloatField(blank=True, null=True)),
                ('rvalue', models.FloatField(blank=True, null=True)),
                ('organism', models.CharField(blank=True, max_length=1024, null=True)),
                ('expression_system', models.CharField(blank=True, max_length=1024, null=True)),
                ('technique', models.CharField(blank=True, max_length=1024, null=True)),
                ('assembly', models.IntegerField(blank=True, null=True)),
                ('skeleton', models.BooleanField()),
            ],
            options={
                'db_table': 'PDBs',
            },
        ),
    ]
