# Generated by Django 2.2 on 2019-09-19 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='residue',
            name='primary',
            field=models.BooleanField(default=True),
        ),
    ]
