# Generated by Django 2.2 on 2019-06-02 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atomium_id', models.IntegerField()),
                ('name', models.CharField(max_length=32)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('z', models.FloatField()),
                ('element', models.CharField(max_length=8)),
                ('residue_name', models.CharField(max_length=32)),
                ('residue_number', models.IntegerField()),
                ('insertion_code', models.CharField(max_length=128)),
                ('chain_id', models.CharField(max_length=128)),
                ('omission_reason', models.TextField(blank=True, null=True)),
                ('pdb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Pdb')),
            ],
            options={
                'db_table': 'metals',
            },
        ),
    ]
