# Generated by Django 2.2 on 2019-06-04 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_metal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chain',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('atomium_id', models.CharField(max_length=128)),
                ('sequence', models.TextField()),
                ('pdb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Pdb')),
            ],
            options={
                'db_table': 'chains',
                'ordering': ['id'],
            },
        ),
    ]
