# Generated by Django 2.2 on 2019-06-04 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_chain'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZincSite',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('family', models.CharField(max_length=128)),
                ('residue_names', models.CharField(max_length=512)),
                ('representative', models.BooleanField(default=False)),
                ('pdb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Pdb')),
            ],
            options={
                'db_table': 'zinc_sites',
            },
        ),
    ]
