# Generated by Django 2.2 on 2019-06-04 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_residue'),
    ]

    operations = [
        migrations.AddField(
            model_name='metal',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ZincSite'),
        ),
        migrations.CreateModel(
            name='Atom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atomium_id', models.IntegerField()),
                ('name', models.CharField(max_length=32)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('z', models.FloatField()),
                ('element', models.CharField(max_length=8)),
                ('residue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Residue')),
            ],
            options={
                'db_table': 'atoms',
            },
        ),
    ]
