# Generated by Django 2.2 on 2019-06-04 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190604_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoordinateBond',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Atom')),
                ('metal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Metal')),
            ],
            options={
                'db_table': 'bonds',
            },
        ),
    ]
