# Generated by Django 2.2 on 2019-06-12 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_coordinatebond'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChainCluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'chain_clusters',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('family', models.CharField(max_length=128)),
                ('keywords', models.CharField(max_length=1024)),
                ('classifications', models.CharField(max_length=1024)),
            ],
            options={
                'db_table': 'groups',
            },
        ),
        migrations.AddField(
            model_name='chain',
            name='cluster',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.ChainCluster'),
        ),
        migrations.AddField(
            model_name='zincsite',
            name='group',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Group'),
        ),
    ]
