# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-26 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZincSite',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
            ],
        ),
    ]
