# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-02 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zincsites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pdb',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('deposition_date', models.DateField()),
            ],
        ),
    ]
