# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-02 10:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zincsites', '0002_pdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Residue',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('residue_id', models.TextField()),
                ('chain', models.TextField()),
                ('name', models.TextField()),
                ('pdb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zincsites.Pdb')),
            ],
        ),
    ]
