# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-02 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zincsites', '0003_residue'),
    ]

    operations = [
        migrations.AddField(
            model_name='zincsite',
            name='residues',
            field=models.ManyToManyField(to='zincsites.Residue'),
        ),
    ]
