# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pdb',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('deposited', models.DateField()),
                ('resolution', models.FloatField()),
                ('checked', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
