# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 13:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zincbind', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Residue',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('residue_id', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=32)),
                ('chain', models.CharField(max_length=16)),
                ('number', models.IntegerField(max_length=32)),
            ],
        ),
        migrations.AlterField(
            model_name='pdb',
            name='id',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='residue',
            name='pdb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zincbind.Pdb'),
        ),
    ]
