# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 14:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zincbind', '0002_auto_20171027_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atom',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('atom_id', models.IntegerField()),
                ('name', models.CharField(max_length=32)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('z', models.FloatField()),
                ('element', models.CharField(max_length=8)),
                ('charge', models.FloatField()),
                ('bfactor', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='residue',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='atom',
            name='residue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zincbind.Residue'),
        ),
    ]
