# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zincbind', '0003_auto_20171027_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZincSite',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('residues', models.ManyToManyField(to='zincbind.Residue')),
            ],
        ),
    ]
