# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zincbind', '0004_zincsite'),
    ]

    operations = [
        migrations.AddField(
            model_name='zincsite',
            name='x',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zincsite',
            name='y',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zincsite',
            name='z',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
