# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zincbind', '0005_auto_20171027_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdb',
            name='checked',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='pdb',
            name='deposited',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pdb',
            name='resolution',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pdb',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
