# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zincbind', '0007_auto_20171027_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdb',
            name='checked',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='pdb',
            name='deposited',
            field=models.DateField(blank=True, null=True),
        ),
    ]
