# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zincbind', '0008_auto_20171027_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdb',
            name='expression',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pdb',
            name='organism',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pdb',
            name='uniprot',
            field=models.TextField(blank=True, null=True),
        ),
    ]
