# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 15:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zincbind', '0009_auto_20171114_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zincsite',
            name='residues',
        ),
        migrations.AddField(
            model_name='zincsite',
            name='pdb',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='zincbind.Pdb'),
            preserve_default=False,
        ),
    ]
