# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 15:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zincbind', '0010_auto_20171114_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residue',
            name='pdb',
        ),
        migrations.AddField(
            model_name='residue',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='zincbind.ZincSite'),
            preserve_default=False,
        ),
    ]
