# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zincbind', '0011_auto_20171114_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residue',
            name='site',
        ),
        migrations.AddField(
            model_name='zincsite',
            name='residues',
            field=models.ManyToManyField(to='zincbind.Residue'),
        ),
    ]
