# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zincbind', '0012_auto_20171114_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='atom',
            name='alpha',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atom',
            name='beta',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atom',
            name='liganding',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
