# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zincbind', '0013_auto_20171114_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdb',
            name='classification',
            field=models.TextField(blank=True, null=True),
        ),
    ]
