# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zincbind', '0014_pdb_classification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdb',
            old_name='uniprot',
            new_name='technique',
        ),
        migrations.AddField(
            model_name='pdb',
            name='rfactor',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
