# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zincbind', '0015_auto_20171118_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residue',
            name='chain',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
