# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-30 11:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zincbind', '0016_auto_20171119_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zincsite',
            name='residues',
        ),
        migrations.AddField(
            model_name='residue',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='zincbind.ZincSite'),
            preserve_default=False,
        ),
    ]
