# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-15 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zincbind', '0017_auto_20171130_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='zincsite',
            name='contrast',
            field=models.TextField(default='[]'),
            preserve_default=False,
        ),
    ]
